name: Echo Example

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  echo-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Echo a string
      run: echo "Hello, GitHub Actions!"
      
    - name: Echo an environment variable  
      env:
        MY_ENV_VAR: ${{ secrets.MY_SECRET }}
      run: echo "The value of MY_ENV_VAR is: $MY_ENV_VAR"
